### ISSUE TITLE
Example for alignment, border, scale ? Since i got not clue how to write them in the mpv file.

### ISSUE THREAD

**Issue by Vortexakhaj** [blue-sky-r/mpv#3]

**Comment by blue-sky-r** [comment]
excerpt from ~/.config/mpv/mpv.config (on linux):

osd-duration=3000
osd-bold=yes
osd-border-size=5
osd-align-x=right
osd-scale-by-window=yes
osd-font-size=85

Full mpv.conf for one of my iPTV running on Asus-EEE located here:
https://github.com/blue-sky-r/Asus-EeePC/blob/master/iptv/eeetv/.config/mpv/mpv.conf

Hope this helps ...
